/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cartela;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author ronal
 */
public class cartelaBingo extends javax.swing.JFrame {

    /**
     * Creates new form cartelaBingo
     */
    
    public static int count = 0;
    public static int faltam = 75-count;
    public static int sorteio[] = new int[75];
    public static int cartela[] = new int[25];
    StringBuilder sorteados = new StringBuilder();
    
    public cartelaBingo() {
        initComponents();
    }
    
    public static int random(){
        int n = (int) (1+Math.random()*(75-1));
        return n;
    }
    
    public void verificaSorteio(){
            if(sorteio[count] == cartela[0]){
                num1.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[1]){
                num2.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[2]){
                num3.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[3]){
                num4.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[4]){
                num5.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[5]){
                num6.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[6]){
                num7.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[7]){
                num8.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[8]){
                num9.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[9]){
                num10.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[10]){
                num11.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[11]){
                num12.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[12]){
                num13.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[13]){
                num14.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[14]){
                num15.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[15]){
                num16.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[16]){
                num17.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[17]){
                num18.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[18]){
                num19.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[19]){
                num20.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[20]){
                num21.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[21]){
                num22.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[22]){
                num23.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[23]){
                num24.setBackground(Color.yellow);
            }else if(sorteio[count] == cartela[24]){
                num25.setBackground(Color.yellow);
            }
    }
    
    public static int[] geraCartela(){
        boolean igual = false;

        for(int i=0; i<25; i++){
            int n = random();
            cartela[i] = n;
            for(int j=i; j>=0; j--){
                if(n == cartela[j]){
                    igual = true;
                    do{ 
                        n = random();
                        if(cartela[j] != n){
                            igual = false;
                            cartela[j] = n;
                        }
                    }while (igual);
                }
            }
        }
        
//        int k = 0;
//        for(int i=0; i<5; i++){
//            for(int j=0; j<5; j++){
//                System.out.print("["+cartela[k++]+"]");
//            }
//            System.out.println("");
//        }
        return cartela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        num1 = new javax.swing.JLabel();
        num6 = new javax.swing.JLabel();
        num11 = new javax.swing.JLabel();
        num16 = new javax.swing.JLabel();
        num21 = new javax.swing.JLabel();
        num22 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num7 = new javax.swing.JLabel();
        num12 = new javax.swing.JLabel();
        num17 = new javax.swing.JLabel();
        num23 = new javax.swing.JLabel();
        num24 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        num8 = new javax.swing.JLabel();
        num9 = new javax.swing.JLabel();
        num13 = new javax.swing.JLabel();
        num14 = new javax.swing.JLabel();
        num18 = new javax.swing.JLabel();
        num19 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        num10 = new javax.swing.JLabel();
        num15 = new javax.swing.JLabel();
        num20 = new javax.swing.JLabel();
        num25 = new javax.swing.JLabel();
        btnSorteio = new javax.swing.JButton();
        lblSorteado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        lblFaltam = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSorteados = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Gerar cartela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        num1.setText("jLabel3");
        num1.setOpaque(true);

        num6.setText("jLabel3");
        num6.setOpaque(true);

        num11.setText("jLabel3");
        num11.setOpaque(true);

        num16.setText("jLabel3");
        num16.setOpaque(true);

        num21.setText("jLabel3");
        num21.setOpaque(true);

        num22.setText("jLabel3");
        num22.setOpaque(true);

        num2.setText("jLabel3");
        num2.setOpaque(true);

        num7.setText("jLabel3");
        num7.setOpaque(true);

        num12.setText("jLabel3");
        num12.setOpaque(true);

        num17.setText("jLabel3");
        num17.setOpaque(true);

        num23.setText("jLabel3");
        num23.setOpaque(true);

        num24.setText("jLabel3");
        num24.setOpaque(true);

        num3.setText("jLabel3");
        num3.setOpaque(true);

        num4.setText("jLabel3");
        num4.setOpaque(true);

        num8.setText("jLabel3");
        num8.setOpaque(true);

        num9.setText("jLabel3");
        num9.setOpaque(true);

        num13.setText("jLabel3");
        num13.setOpaque(true);

        num14.setText("jLabel3");
        num14.setOpaque(true);

        num18.setText("jLabel3");
        num18.setOpaque(true);

        num19.setText("jLabel3");
        num19.setOpaque(true);

        num5.setText("jLabel3");
        num5.setOpaque(true);

        num10.setText("jLabel3");
        num10.setOpaque(true);

        num15.setText("jLabel3");
        num15.setOpaque(true);

        num20.setText("jLabel3");
        num20.setOpaque(true);

        num25.setText("jLabel3");
        num25.setOpaque(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num24, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        btnSorteio.setText("Sortear número");
        btnSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteioActionPerformed(evt);
            }
        });

        lblSorteado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblSorteado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSorteado.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Números sorteados:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Faltam:");

        lblCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCount.setText("0");

        lblFaltam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFaltam.setText("75");

        jScrollPane1.setViewportView(txtAreaSorteados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSorteio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSorteado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCount)
                            .addComponent(lblFaltam)))
                    .addComponent(jScrollPane1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSorteio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSorteado, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(lblFaltam)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblCount)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int cartela[] = geraCartela();
        num1.setText(String.valueOf(cartela[0]));
        num2.setText(String.valueOf(cartela[1]));
        num3.setText(String.valueOf(cartela[2]));
        num4.setText(String.valueOf(cartela[3]));
        num5.setText(String.valueOf(cartela[4]));
        num6.setText(String.valueOf(cartela[5]));
        num7.setText(String.valueOf(cartela[6]));
        num8.setText(String.valueOf(cartela[7]));
        num9.setText(String.valueOf(cartela[8]));
        num10.setText(String.valueOf(cartela[9]));
        num11.setText(String.valueOf(cartela[10]));
        num12.setText(String.valueOf(cartela[11]));
        num13.setText(String.valueOf(cartela[12]));
        num14.setText(String.valueOf(cartela[13]));
        num15.setText(String.valueOf(cartela[14]));
        num16.setText(String.valueOf(cartela[15]));
        num17.setText(String.valueOf(cartela[16]));
        num18.setText(String.valueOf(cartela[17]));
        num19.setText(String.valueOf(cartela[18]));
        num20.setText(String.valueOf(cartela[19]));
        num21.setText(String.valueOf(cartela[20]));
        num22.setText(String.valueOf(cartela[21]));
        num23.setText(String.valueOf(cartela[22]));
        num24.setText(String.valueOf(cartela[23]));
        num25.setText(String.valueOf(cartela[24]));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteioActionPerformed
        // TODO add your handling code here:
        boolean igual = true;
        System.out.println(count);
        if(count == 0){
            sorteio[count] = random();
        }else{
            do{
               int n = random();
               for(int i=count; i>0; i--){
                   if(sorteio[i] != n){
                       igual = false;
                       sorteio[count] = n;
                   }
               }
           }while(igual);   
        }
        
        lblSorteado.setText(String.valueOf(sorteio[count]).toString());
        lblCount.setText(String.valueOf(count+1).toString());
        lblFaltam.setText(String.valueOf(75-(count+1)).toString());
        
        sorteados = sorteados.append(Integer.valueOf(sorteio[count]).toString());
        sorteados = sorteados.append(",");
//        if(){
//            sorteados = sorteados.append("\n");
//        }
        txtAreaSorteados.setText(sorteados.toString());
        
        verificaSorteio();
        count++;
    }//GEN-LAST:event_btnSorteioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cartelaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cartelaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cartelaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cartelaBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {;
            public void run() {
                new cartelaBingo().setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSorteio;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblFaltam;
    private javax.swing.JLabel lblSorteado;
    private static javax.swing.JLabel num1;
    private javax.swing.JLabel num10;
    private javax.swing.JLabel num11;
    private javax.swing.JLabel num12;
    private javax.swing.JLabel num13;
    private javax.swing.JLabel num14;
    private javax.swing.JLabel num15;
    private javax.swing.JLabel num16;
    private javax.swing.JLabel num17;
    private javax.swing.JLabel num18;
    private javax.swing.JLabel num19;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num20;
    private javax.swing.JLabel num21;
    private javax.swing.JLabel num22;
    private javax.swing.JLabel num23;
    private javax.swing.JLabel num24;
    private javax.swing.JLabel num25;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num5;
    private static javax.swing.JLabel num6;
    private javax.swing.JLabel num7;
    private javax.swing.JLabel num8;
    private javax.swing.JLabel num9;
    private javax.swing.JTextPane txtAreaSorteados;
    // End of variables declaration//GEN-END:variables
}
